language: python
cache: pip

env:
  global:
    - DJANGO_SETTINGS_MODULE="tests.app.settings"
    - TOX_ENV=
  matrix:
    - TOX_ENV=flake8,isort


python:
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO='111' WAGTAIL='20'
  - DJANGO='111' WAGTAIL='21'
  - DJANGO='20' WAGTAIL='20'
  - DJANGO='20' WAGTAIL='21'


matrix:
  include:
    - env: TOX_ENV='flake8,isort'
      python: 3.5

before_install:
    - sudo add-apt-repository ppa:mc3man/trusty-media -y
    - sudo apt-get update -qq
    # The install of ffmpeg fails at random with 'There were unauthenticated packages' ü§∑‚Äç‚ôÇÔ∏è
    - sudo apt-get install ffmpeg --allow-unauthenticated -y

install:
  - pip install --upgrade pip wheel tox

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/virtualenv

script:
  # Run tox using either a specific environment from TOX_ENV,
  # or building one from the environment variables
  - tox -e "${TOX_ENV:-py${TRAVIS_PYTHON_VERSION/./}-dj${DJANGO}-wt${WAGTAIL}}"
